### ISSUE TITLE
Turkish Update (json file included)

### ISSUE THREAD

**Issue by GameVPR** [notrhys/anticheat-test.com-translations#22]
## Pros
+ [+] More accurate.
+ [+] More understanable.
+ [+] Translated the untranslated words.
+ [~] Fixed some typos.

## Links
| Vendor | Link |
| -------- | ---- |
| Pastebin | https://pastebin.com/1sG1emkf |
| Hastebin | https://hastebin.com/share/iposuduwok.json |
| ControlC | https://controlc.com/cb0f8e99 |
| Nekobin | https://nekobin.com/dotuhivasa |

## Info
IGN: GameVPR
Made by GameVPR

**Comment by Thuy2y2c** [comment]
you could just send a pull request

**Comment by notrhys** [comment]
make a pr next time, pushed anyway
